### ISSUE TITLE
DS3505 Traceback altimeter KeyError

### ISSUE THREAD

**Issue by akrherz** [akrherz/pyIEM#242]
spotted in the wild today

```
Traceback (most recent call last):
  File "ingest_isd.py", line 103, in <module>
    main(sys.argv)
  File "ingest_isd.py", line 68, in main
    data = ds3505.parser(line.strip(), faa, add_metar=True)
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/pyiem/ncei/ds3505.py", line 1686, in parser
    gen_metar(data)
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/pyiem/ncei/ds3505.py", line 1568, in gen_metar
    and data["extra"]["MA1"]["altimeter"] is not None
KeyError: 'altimeter'
```

**Comment by akrherz** [comment]
more info:

<details>
{
 "airtemp_c": null,
 "airtemp_c_qc": "9",
 "call_id": "KBRO",
 "ceiling_m": null,
 "ceiling_m_cavok": "N",
 "ceiling_m_how": "9",
 "ceiling_m_qc": "9",
 "chars": "0233",
 "dewpointtemp_c": null,
 "dewpointtemp_c_qc": "9",
 "drct": null,
 "drct_qc": "9",
 "elevation": 6.0,
 "extra": {
  "AA1": {
   "cond_code": "9",
   "depth": 0.0,
   "hours": 1,
   "qc": "5"
  },
  "AA2": {
   "cond_code": "9",
   "depth": 0.0,
   "hours": 6,
   "qc": "1"
  },
  "AG1": {
   "code": "0",
   "depth": "000"
  },
  "EQD": {
   "Q01": "+000002VOVAR "
  },
  "GP1": {
   "diffuse_horizontal": "0199",
   "diffuse_horizontal_flag": "01",
   "diffuse_horizontal_uncertainty": "028",
   "direct_normal": "0691",
   "direct_normal_flag": "01",
   "direct_normal_uncertainty": "031",
   "global_horizontal": "0671",
   "global_horizontal_flag": "01",
   "global_horizontal_uncertainty": "028",
   "time": "0060"
  },
  "GQ1": {
   "azimuth_angle": "1559",
   "azimuth_angle_qc": "9",
   "time": "0060",
   "zenith_angle": "0469",
   "zenith_angle_qc": "9"
  },
  "GR1": {
   "horizontal": "0962",
   "horizontal_qc": "9",
   "normal": "1409",
   "normal_qc": "9",
   "time": "0060"
  },
  "MA1": {},
  "MW1": {
   "code": "00",
   "qc": "1"
  },
  "QNN": {},
  "REM": {
   "AWY": "025/ TIDE DEP 00/// 58012 6//// 1//// 2//// PWINO PRESFR $;"
  }
 },
 "hhmi": "1800",
 "lat": 25.9,
 "lon": -97.433,
 "mslp_hpa": 1024.5,
 "mslp_hpa_qc": "5",
 "qc_process": "V020",
 "report_type": "SAO  ",
 "srcflag": "3",
 "stationid": "722500",
 "valid": "1995-01-31 18:00:00+00:00",
 "vsby_m": null,
 "vsby_m_qc": "9",
 "vsby_m_variable": "N",
 "vsby_m_variable_qc": "9",
 "wban": "12919",
 "wind_code": "9",
 "wind_speed_mps": null,
 "wind_speed_mps_qc": "9",
 "yyyymmdd": "19950131"
}
</details>
