### ISSUE TITLE
Product cannot be parsed if NWS date does not start on its own line

### ISSUE THREAD

**Issue by mzuranski** [akrherz/pyIEM#320]
The attached text product (LSR from TBW) throws an error, code to reproduce is below.

```
Python 3.4.5 | packaged by conda-forge | (default, Sep  8 2016, 14:22:44)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyiem.nws.products import parser as text_parser
>>> with open("202011121555.txt") as file:
...     tp = text_parser(file.read())
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/ldm/anaconda/envs/text/lib/python3.4/site-packages/pyIEM-0.12.0-py3.4.egg/pyiem/nws/products/__init__.py", line 57, in parser
    return lsr.parser(text, utcnow, ugc_provider, nwsli_provider)
  File "/home/ldm/anaconda/envs/text/lib/python3.4/site-packages/pyIEM-0.12.0-py3.4.egg/pyiem/nws/products/lsr.py", line 251, in parser
    lsr = parse_lsr(prod, "".join(match.groups()))
  File "/home/ldm/anaconda/envs/text/lib/python3.4/site-packages/pyIEM-0.12.0-py3.4.egg/pyiem/nws/products/lsr.py", line 199, in parse_lsr
    lsr.assign_timezone(prod.tz, prod.z)
  File "/home/ldm/anaconda/envs/text/lib/python3.4/site-packages/pyIEM-0.12.0-py3.4.egg/pyiem/nws/lsr.py", line 142, in assign_timezone
    hours=reference.offsets[z]
KeyError: None
>>>

```

The offending part of the text file:
> PRELIMINARY LOCAL STORM REPORT...SUMMARY
> NATIONAL WEATHER SERVICE TAMPA BAY 
> RUSKIN FL 1052 AM EST THU NOV 12 2020

Correcting that text to this will allow the product to be parsed without error:

> PRELIMINARY LOCAL STORM REPORT...SUMMARY
> NATIONAL WEATHER SERVICE TAMPA BAY RUSKIN FL
> 1052 AM EST THU NOV 12 2020

[202011121555.txt](https://github.com/akrherz/pyIEM/files/5532537/202011121555.txt)

**Comment by akrherz** [comment]
Thanks, hehe, my ingestor bombed the same way.  I suppose I could account for this :)  Additionally, do you think failing to parse the timestamp should be fatal ?

**Comment by akrherz** [comment]
Note that present master pyIEM bombs in this manner

```
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/pyiem/nws/products/lsr.py", line 212, in parser
    lsr = parse_lsr(prod, "".join(match.groups()))
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/pyiem/nws/products/lsr.py", line 154, in parse_lsr
    lsr.assign_timezone(prod.tz, prod.z)
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/pyiem/nws/lsr.py", line 230, in assign_timezone
    self.utcvalid = self.valid + timedelta(hours=reference.offsets[z])
builtins.KeyError: None
```

**Comment by mzuranski** [comment]
>Additionally, do you think failing to parse the timestamp should be fatal ?

Tough call, I feel like that'd depend on the use case.  Maybe fail back to the WMO header date/time if the NWS date/time can't be parsed, but then you'd lose the local time zone wouldn't you?  That may matter more to some than to others.

>I suppose I could account for this

I think attempting to handle that error would be preferred, what happens if it can't be handled is more subjective.

**Comment by akrherz** [comment]
> but then you'd lose the local time zone wouldn't you?

For LSRs, this is fatal as I need the timezone to know the timestamp of the individual LSRs.  PR pending...

**Comment by akrherz** [comment]
This should be fixed going forward, do you want some sort of patch for your installed version 0.12.0 or you want me to make a new release?  My API is likely not stable enough to jump to 0.19.0 without some checking :(

**Comment by mzuranski** [comment]
No need to do anything specifically for me (though I do appreciate the offer).  I might not be able to address things on my side for a little while anyways.  I mostly wanted to report the issue; your response time is impressively quick!
